version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "pycodestyle found no issues!"
      - ./run_all_unittests.sh
artifacts:
  files:
    - ./..
  discard-paths: yes
  base-directory: .
  name: python-app.zip
